### PR TITLE
Gatlab next

### PR DESCRIPTION
**Pull request by olynch**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
I see that the sciml integration got cut in this PR. What is the plan there?

**Comment by olynch** [comment]
> I see that the sciml integration got cut in this PR. What is the plan there?

Even though it was in a package extension, it got loaded for the tests, which made our tests run 5x slower. I think that it should just be in a separate package.

**Comment by jpfairbanks** [comment]
I get that testing against MTK brings in a lot of dependencies, but we could still do the `@lens` construction to make the ODE and then interpret it directly (by using substitution of numbers for variables and evaluation of the primitive functions) and do our own Euler's method as an example of using the package for the docs. 

I tried to uncomment out the following from the Theories.Algebra module

```julia

# @theory ThAb <: ThMonoid begin
#   using ThGroup
#   using ThCMonoid
# end

# @theory ThRing <: ThSet begin
#   using ThAb: ⋅ as +, i as -, e as zero
#   using ThMonoid: ⋅ as *, e as one
#   a * (b + c) == (a * b) + (a * c) ⊣ [a,b,c]
# end

# @theory ThCRing <: ThRing begin
#   a * b == b * a ⊣ [a,b]
# end

# @theory ThRig <: ThSet begin
#   using ThCMonoid: ⋅ as +, e as zero
#   using ThMonoid: ⋅ as *, e as one
#   a * (b + c) == (a * b) + (a * c) ⊣ [a,b,c]
# end

# @theory ThCRig <: ThRig begin
#   a * b == b * a ⊣ [a,b]
# end

# @theory ThElementary <: ThCRing begin
#   sin(x) ⊣ [x]
#   cos(x) ⊣ [x]
#   tan(x) ⊣ [x]
#   exp(x) ⊣ [x]
#   sigmoid(x) ⊣ [x]
# end
```

but it looks like the `using` thing is broken. Is there an updated version of the `using` syntax?

**Comment by olynch** [comment]
> I get that testing against MTK brings in a lot of dependencies, but we could still do the `@lens` construction to make the ODE and then interpret it directly (by using substitution of numbers for variables and evaluation of the primitive functions) and do our own Euler's method as an example of using the package for the docs.

Yeah, we should definitely do this. Gotta love the 5 line Euler's method in Julia.

**Pull request merged**
